### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by zsaddf** [lllbbbyyy/CriticalPath#1]
我把您的代码拷到idea中发现init.js中var使用错误，而且var chart_object = {};var chart_object2 = {};这两个代码也没法用导致chart_object 和chart_object2 出错，并且我编译时只能出现初始的写数据界面并不能出现关键路径的那些线路图，请问我是少下载了包吗，还是有其他东西没有添加，我添加了elercon但是没有用。请您有空时可以帮我回答一下吗？谢谢。

**Comment by lllbbbyyy** [comment]
> 我把您的代码拷到idea中发现init.js中var使用错误，而且var chart_object = {};var chart_object2 = {};这两个代码也没法用导致chart_object 和chart_object2 出错，并且我编译时只能出现初始的写数据界面并不能出现关键路径的那些线路图，请问我是少下载了包吗，还是有其他东西没有添加，我添加了elercon但是没有用。请您有空时可以帮我回答一下吗？谢谢。

我不是很清楚你把代码拷贝到idea中的目的是什么，在我的印象中idea主要是用来编写java程序的ide
如果你是想要在不通过electron启动的情况下看一看运行效果，那么可以通过浏览器打开index.html进行查看
直接通过浏览器查看确实会报错，但是报错内容应当是你说的两行代码上面，尝试获取electron对象失败导致的
```cpp
var { remote } = require('electron');
```
你可以通过将其注释掉从而使其能够在浏览器中正常运行，这行代码在[init.js文件的第四行](https://github.com/lllbbbyyy/CriticalPath/blob/7246a982e886f68f5a8945aebe4bb4795717307b/src/js/init.js#L4)

**Comment by zsaddf** [comment]
好的，谢谢您



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Boyu ***@***.***&gt;; 
发送时间: 2022年6月12日(星期天) 下午2:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lllbbbyyy/CriticalPath] 你好 (Issue #1)





  
我把您的代码拷到idea中发现init.js中var使用错误，而且var chart_object = {};var chart_object2 = {};这两个代码也没法用导致chart_object 和chart_object2 出错，并且我编译时只能出现初始的写数据界面并不能出现关键路径的那些线路图，请问我是少下载了包吗，还是有其他东西没有添加，我添加了elercon但是没有用。请您有空时可以帮我回答一下吗？谢谢。
  
我不是很清楚你把代码拷贝到idea中的目的是什么，在我的印象中idea主要是用来编写java程序的ide
 如果你是想要在不通过electron启动的情况下看一看运行效果，那么可以通过浏览器打开index.html进行查看
 直接通过浏览器查看确实会报错，但是报错内容应当是你说的两行代码上面，尝试获取electron对象失败导致的
 var { remote } = require('electron');
 
你可以通过将其注释掉从而使其能够在浏览器中正常运行，这行代码在init.js文件的第四行
